require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ComodosController do

  def mock_comodo(stubs={})
    @mock_comodo ||= mock_model(Comodo, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all comodos as @comodos" do
      Comodo.stub(:all) { [mock_comodo] }
      get :index
      assigns(:comodos).should eq([mock_comodo])
    end
  end

  describe "GET show" do
    it "assigns the requested comodo as @comodo" do
      Comodo.stub(:find).with("37") { mock_comodo }
      get :show, :id => "37"
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "GET new" do
    it "assigns a new comodo as @comodo" do
      Comodo.stub(:new) { mock_comodo }
      get :new
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "GET edit" do
    it "assigns the requested comodo as @comodo" do
      Comodo.stub(:find).with("37") { mock_comodo }
      get :edit, :id => "37"
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created comodo as @comodo" do
        Comodo.stub(:new).with({'these' => 'params'}) { mock_comodo(:save => true) }
        post :create, :comodo => {'these' => 'params'}
        assigns(:comodo).should be(mock_comodo)
      end

      it "redirects to the created comodo" do
        Comodo.stub(:new) { mock_comodo(:save => true) }
        post :create, :comodo => {}
        response.should redirect_to(comodo_url(mock_comodo))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comodo as @comodo" do
        Comodo.stub(:new).with({'these' => 'params'}) { mock_comodo(:save => false) }
        post :create, :comodo => {'these' => 'params'}
        assigns(:comodo).should be(mock_comodo)
      end

      it "re-renders the 'new' template" do
        Comodo.stub(:new) { mock_comodo(:save => false) }
        post :create, :comodo => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comodo" do
        Comodo.stub(:find).with("37") { mock_comodo }
        mock_comodo.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :comodo => {'these' => 'params'}
      end

      it "assigns the requested comodo as @comodo" do
        Comodo.stub(:find) { mock_comodo(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:comodo).should be(mock_comodo)
      end

      it "redirects to the comodo" do
        Comodo.stub(:find) { mock_comodo(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(comodo_url(mock_comodo))
      end
    end

    describe "with invalid params" do
      it "assigns the comodo as @comodo" do
        Comodo.stub(:find) { mock_comodo(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:comodo).should be(mock_comodo)
      end

      it "re-renders the 'edit' template" do
        Comodo.stub(:find) { mock_comodo(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comodo" do
      Comodo.stub(:find).with("37") { mock_comodo }
      mock_comodo.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the comodos list" do
      Comodo.stub(:find) { mock_comodo }
      delete :destroy, :id => "1"
      response.should redirect_to(comodos_url)
    end
  end

end
