require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe ComodosController do
  
  before do
    @residencia = Factory.create :residencia
    @usuario = @residencia.usuario
  end
  
  def mock_comodo(stubs={})
    @mock_comodo ||= mock_model(Comodo, stubs).as_null_object
  end

  describe "GET show" do
    it "assigns the requested comodo as @comodo" do
      Comodo.stub(:find).with("37") { mock_comodo }
      get :show, :id => "37", :usuario_id => @usuario.id, :residencia_id => @residencia.id
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "GET new" do
    it "assigns a new comodo as @comodo" do
      Comodo.stub(:new) { mock_comodo }
      get :new, :usuario_id => @usuario.id, :residencia_id => @residencia.id
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "GET edit" do
    it "assigns the requested comodo as @comodo" do
      Comodo.stub(:find).with("37") { mock_comodo }
      get :edit, :id => "37", :usuario_id => @usuario.id, :residencia_id => @residencia.id
      assigns(:comodo).should be(mock_comodo)
    end
  end

  describe "POST create" do
    before do 
      @params = { 
          :residencia_id => @residencia.id,
          :usuario_id => @usuario.id,
          :comodo => { :nome => 'cozinha' }
      }
    end
    
    describe "with valid params" do
      it "cria um comodo" do
        post :create, @params
        assigns(:comodo).should be
        response.should redirect_to(:controller => :residencias, 
                                                    :action => :show, 
                                                    :id => @residencia.id, 
                                                    :usuario_id => @usuario.id)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comodo as @comodo" do
        @params[:comodo][:nome] = ""
        post :create, @params
        assigns(:comodo).should be
        
        response.should render_template :new
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "deveria atualizar o comodo" do
        comodo = Factory.create :comodo
        
        params = {
          :id => comodo.id,
          :residencia_id => comodo.residencia.id,
          :usuario_id => comodo.residencia.id,
          :comodo => {
            :nome => "Novo Nome"
          }
        }
        
        put :update, params
        
        comodo_atualizado = assigns(:comodo)
        comodo_atualizado.should_not be_nil
        comodo_atualizado.nome.should eql("Novo Nome")
        
        flash[:notice].should_not be_blank
        
        response.should redirect_to :controller => :residencias,
                                    :action => :show,
                                    :id => comodo.residencia.id,
                                    :usuario_id => comodo.residencia.usuario.id
      end
    end

    describe "with invalid params" do
      it "deveria manter @comodo" do
        comodo = Factory.create :comodo
        
        params = {
          :id => comodo.id,
          :residencia_id => comodo.residencia.id,
          :usuario_id => comodo.residencia.id,
          :comodo => {
            :nome => ''
          }
        }
        
        put :update, params
        
        comodo_atualizado = assigns(:comodo)
        comodo_atualizado.new_record?.should be_false
        comodo.reload.nome.should eql(comodo.nome)
        
        response.should render_template :edit
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comodo" do
      comodo = Factory.create :comodo
      delete :destroy, :id => comodo.id, :usuario_id => comodo.residencia.usuario.id, :residencia_id => comodo.residencia.id
  
      response.should redirect_to :controller => :residencias,
                                  :action => :show,
                                  :id => comodo.residencia.id,
                                  :usuario_id => comodo.residencia.usuario.id
    end
  end

end
