require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PerifericosController do

  before do
    @periferico = Factory.create :periferico
    @comodo = @periferico.comodo
    @residencia = @periferico.comodo.residencia
    @usuario = @periferico.comodo.residencia.usuario

    @valid_params = {
      :usuario_id => @usuario.id,
      :residencia_id => @residencia.id,
      :comodo_id => @comodo.id,
      :periferico => {
        :nome => 'teste de periferico',
        :pino => '1'
      }
    }
  end

  it 'deveria criar um periferico' do
    xhr :post, :create, @valid_params
    assigns(:periferico).should be
  end

  describe "with valid params" do
    it "cria um periferico" do
      post :create, @valid_params
      assigns(:periferico).should be
      flash[:notice].should_not be_blank
    end
  end

  describe "GET new" do
    it "assigns a new comodo as @periferico" do
      get :new, :usuario_id => @usuario.id, :residencia_id => @residencia.id, :comodo_id => @comodo.id

      assigns(:periferico).should be
      assigns(:periferico).comodo.should be
      assigns(:periferico).comodo.residencia.should be
      assigns(:periferico).comodo.residencia.usuario.should be

    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comodo" do
      delete :destroy, :id => @periferico.id,
                       :comodo_id => @comodo.id,
                       :usuario_id => @usuario.id,
                       :residencia_id => @residencia.id

      response.should redirect_to :controller => :comodos,
                                  :action => :show,
                                  :id => @periferico.comodo.id,
                                  :residencia_id => @residencia.id,
                                  :usuario_id => @usuario.id
    end
  end

  describe "PUT update" do
      it "deveria atualizar o periferico" do
        params = {
          :id => @periferico.id,
          :comodo_id => @comodo.id,
          :residencia_id => @residencia.id,
          :usuario_id => @usuario.id,
          :periferico => {
            :nome => "Novo Nome",
            :pino => "1"
          }
        }

        put :update, params

        periferico_atualizado = assigns(:periferico)
        periferico_atualizado.should_not be_nil
        periferico_atualizado.nome.should eql("Novo Nome")

        flash[:notice].should_not be_blank

        response.should redirect_to :controller => :comodos,
                                    :action => :show,
                                    :id => @periferico.comodo.id,
                                    :residencia_id => @residencia.id,
                                    :usuario_id => @usuario.id
      end
  end
end

