require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PerifericosController do

  def mock_periferico(stubs={})
    @mock_periferico ||= mock_model(Periferico, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all perifericos as @perifericos" do
      Periferico.stub(:all) { [mock_periferico] }
      get :index
      assigns(:perifericos).should eq([mock_periferico])
    end
  end

  describe "GET show" do
    it "assigns the requested periferico as @periferico" do
      Periferico.stub(:find).with("37") { mock_periferico }
      get :show, :id => "37"
      assigns(:periferico).should be(mock_periferico)
    end
  end

  describe "GET new" do
    it "assigns a new periferico as @periferico" do
      Periferico.stub(:new) { mock_periferico }
      get :new
      assigns(:periferico).should be(mock_periferico)
    end
  end

  describe "GET edit" do
    it "assigns the requested periferico as @periferico" do
      Periferico.stub(:find).with("37") { mock_periferico }
      get :edit, :id => "37"
      assigns(:periferico).should be(mock_periferico)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created periferico as @periferico" do
        Periferico.stub(:new).with({'these' => 'params'}) { mock_periferico(:save => true) }
        post :create, :periferico => {'these' => 'params'}
        assigns(:periferico).should be(mock_periferico)
      end

      it "redirects to the created periferico" do
        Periferico.stub(:new) { mock_periferico(:save => true) }
        post :create, :periferico => {}
        response.should redirect_to(periferico_url(mock_periferico))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved periferico as @periferico" do
        Periferico.stub(:new).with({'these' => 'params'}) { mock_periferico(:save => false) }
        post :create, :periferico => {'these' => 'params'}
        assigns(:periferico).should be(mock_periferico)
      end

      it "re-renders the 'new' template" do
        Periferico.stub(:new) { mock_periferico(:save => false) }
        post :create, :periferico => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested periferico" do
        Periferico.stub(:find).with("37") { mock_periferico }
        mock_periferico.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :periferico => {'these' => 'params'}
      end

      it "assigns the requested periferico as @periferico" do
        Periferico.stub(:find) { mock_periferico(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:periferico).should be(mock_periferico)
      end

      it "redirects to the periferico" do
        Periferico.stub(:find) { mock_periferico(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(periferico_url(mock_periferico))
      end
    end

    describe "with invalid params" do
      it "assigns the periferico as @periferico" do
        Periferico.stub(:find) { mock_periferico(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:periferico).should be(mock_periferico)
      end

      it "re-renders the 'edit' template" do
        Periferico.stub(:find) { mock_periferico(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested periferico" do
      Periferico.stub(:find).with("37") { mock_periferico }
      mock_periferico.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the perifericos list" do
      Periferico.stub(:find) { mock_periferico }
      delete :destroy, :id => "1"
      response.should redirect_to(perifericos_url)
    end
  end

end
