require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PerifericosController do
  
  it 'deveria criar um periferico'
  it 'deveria atualizar um periferico' 
  it 'deveria renderizar o new'
  it 'deveria renderizar o edit'
  it 'deveria excluir um periferico'
  
end
